// Code generated by "stringer -type PadShapes"; DO NOT EDIT

package gokicadlib

import "fmt"

const _PadShapes_name = "circlerectovaltrapezoid"

var _PadShapes_index = [...]uint8{0, 6, 10, 14, 23}

func (i PadShapes) String() string {
	if i < 0 || i >= PadShapes(len(_PadShapes_index)-1) {
		return fmt.Sprintf("PadShapes(%d)", i)
	}
	return _PadShapes_name[_PadShapes_index[i]:_PadShapes_index[i+1]]
}

var _PadShapesNameToValue_map = map[string]PadShapes{
	_PadShapes_name[0:6]:   0,
	_PadShapes_name[6:10]:  1,
	_PadShapes_name[10:14]: 2,
	_PadShapes_name[14:23]: 3,
}

func PadShapesString(s string) (PadShapes, error) {
	if val, ok := _PadShapesNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PadShapes values", s)
}
