// Code generated by "stringer -type PadTypes"; DO NOT EDIT

package gokicadlib

import "fmt"

const _PadTypes_name = "thru_holesmdconnectnp_thru_hole"

var _PadTypes_index = [...]uint8{0, 9, 12, 19, 31}

func (i PadTypes) String() string {
	if i < 0 || i >= PadTypes(len(_PadTypes_index)-1) {
		return fmt.Sprintf("PadTypes(%d)", i)
	}
	return _PadTypes_name[_PadTypes_index[i]:_PadTypes_index[i+1]]
}

var _PadTypesNameToValue_map = map[string]PadTypes{
	_PadTypes_name[0:9]:   0,
	_PadTypes_name[9:12]:  1,
	_PadTypes_name[12:19]: 2,
	_PadTypes_name[19:31]: 3,
}

func PadTypesString(s string) (PadTypes, error) {
	if val, ok := _PadTypesNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PadTypes values", s)
}
